In [7]:
from ib_async import *

util.startLoop()

ib = IB()
ib.connect("127.0.0.1", 7497, clientId=15)

In [8]:
contracts = [
    Forex(pair) for pair in ("EURUSD", "USDJPY", "GBPUSD", "USDCHF", "USDCAD", "AUDUSD")
]
ib.qualifyContracts(*contracts)

eurusd = contracts[2]

In [11]:
import datetime

start = ""
end = datetime.datetime.now()
ticks = ib.reqHistoricalTicks(eurusd, start, end, 1000, "Midpoint", useRth=False)
ticks

[HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 21, tzinfo=datetime.timezone.utc), price=1.340625, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.34062, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.340615, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.340605, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.34065, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.340655, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.34067, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.34069, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.3407, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.340695, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.3407, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.34075, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.340745, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.34076, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.340765, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.34075, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 23, tzinfo=datetime.timezone.utc), price=1.340765, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34076, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340755, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34075, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340745, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34073, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340695, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.3407, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340705, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34071, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340755, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340765, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340755, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340765, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340755, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34076, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340775, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34076, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340775, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340785, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340775, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.3408, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34083, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34084, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340845, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34086, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340855, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34086, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340855, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34086, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340845, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34086, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340845, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34086, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340845, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34084, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340845, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34085, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34086, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.340855, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 24, tzinfo=datetime.timezone.utc), price=1.34086, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 26, tzinfo=datetime.timezone.utc), price=1.34085, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 26, tzinfo=datetime.timezone.utc), price=1.34084, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 26, tzinfo=datetime.timezone.utc), price=1.340795, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 26, tzinfo=datetime.timezone.utc), price=1.340765, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 26, tzinfo=datetime.timezone.utc), price=1.34075, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 26, tzinfo=datetime.timezone.utc), price=1.34074, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 26, tzinfo=datetime.timezone.utc), price=1.340715, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 27, tzinfo=datetime.timezone.utc), price=1.34075, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 27, tzinfo=datetime.timezone.utc), price=1.340745, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 27, tzinfo=datetime.timezone.utc), price=1.340785, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 27, tzinfo=datetime.timezone.utc), price=1.340765, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 27, tzinfo=datetime.timezone.utc), price=1.340745, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 29, tzinfo=datetime.timezone.utc), price=1.34076, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 29, tzinfo=datetime.timezone.utc), price=1.340755, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 29, tzinfo=datetime.timezone.utc), price=1.34076, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 29, tzinfo=datetime.timezone.utc), price=1.34075, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 29, tzinfo=datetime.timezone.utc), price=1.34074, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 29, tzinfo=datetime.timezone.utc), price=1.340715, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34072, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34074, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34073, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.340725, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34073, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34074, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.340765, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34076, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.340745, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.340755, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34077, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34076, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34077, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.340775, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34079, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.340795, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.3408, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34079, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.340795, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.3408, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.340835, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34084, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34085, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 30, tzinfo=datetime.timezone.utc), price=1.34086, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340855, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340805, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.3408, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34079, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340785, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34079, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340785, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340775, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34078, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340775, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34078, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340835, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34083, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34078, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340785, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34079, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34078, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34079, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340795, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34079, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340795, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34079, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340785, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34078, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340775, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340755, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34071, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34072, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340725, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340735, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34074, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340745, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340755, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34076, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340765, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.34077, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 35, tzinfo=datetime.timezone.utc), price=1.340775, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.34076, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340755, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340745, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.34074, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340725, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340715, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.34072, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340725, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.34073, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340735, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340685, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.34068, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340685, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.34068, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340685, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340675, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340685, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340675, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340685, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.34069, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340685, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.3407, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.340725, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 36, tzinfo=datetime.timezone.utc), price=1.34077, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 37, tzinfo=datetime.timezone.utc), price=1.340735, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 37, tzinfo=datetime.timezone.utc), price=1.34072, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 37, tzinfo=datetime.timezone.utc), price=1.34071, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 37, tzinfo=datetime.timezone.utc), price=1.340695, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 37, tzinfo=datetime.timezone.utc), price=1.3407, size=0.0),
 HistoricalTick(time=datetime.datetime(2026, 3, 6, 21, 56, 37, tzinfo=datetime.timezone.utc), price=1.34071, size=0.0),

In [12]:
df=util.df(ticks)
df

                          time     price  size
0    2026-03-06 21:56:21+00:00  1.340625   0.0
1    2026-03-06 21:56:23+00:00  1.340620   0.0
2    2026-03-06 21:56:23+00:00  1.340615   0.0
3    2026-03-06 21:56:23+00:00  1.340605   0.0
4    2026-03-06 21:56:23+00:00  1.340650   0.0
...                        ...       ...   ...
999  2026-03-06 21:59:59+00:00  1.340925   0.0
1000 2026-03-06 21:59:59+00:00  1.340825   0.0
1001 2026-03-06 21:59:59+00:00  1.341115   0.0
1002 2026-03-06 21:59:59+00:00  1.340850   0.0
1003 2026-03-06 21:59:59+00:00  1.340080   0.0

[1004 rows x 3 columns]

In [6]:
df.tail(10)

                          time     price  size
994  2026-03-06 21:59:58+00:00  1.341580   0.0
995  2026-03-06 21:59:59+00:00  1.341555   0.0
996  2026-03-06 21:59:59+00:00  1.341410   0.0
997  2026-03-06 21:59:59+00:00  1.341390   0.0
998  2026-03-06 21:59:59+00:00  1.341375   0.0
999  2026-03-06 21:59:59+00:00  1.340925   0.0
1000 2026-03-06 21:59:59+00:00  1.340825   0.0
1001 2026-03-06 21:59:59+00:00  1.341115   0.0
1002 2026-03-06 21:59:59+00:00  1.340850   0.0
1003 2026-03-06 21:59:59+00:00  1.340080   0.0